### ISSUE TITLE
Add more core NumPy Functions

### ISSUE THREAD

**Issue by hameerabbasi** [Quansight-Labs/unumpy#6]
- [x] `broadcast_arrays`/`broadcast_to` (Quansight-Labs/uarray#150)
- [x]  `concatenate`/`stack` (Quansight-Labs/uarray#151)
- [x] `errstate` (#17)
- [x] `pad` (#12)
- [x] [Set routines](https://www.numpy.org/devdocs/reference/routines.set.html) (Quansight-Labs/uarray#144)
  - [x] `unique`
  - [x] `in1d`
  - [x] `intersect1d`
  - [x] `isin`
  - [x] `setdiff1d`
  - [x] `setxor1d`
  - [x] `union1d`
- [x] [Sorting routines](https://www.numpy.org/devdocs/reference/routines.sort.html#sorting)
  - [x] `sort` (Quansight-Labs/uarray#145)
  - [x] `lexsort` (Quansight-Labs/uarray#145)
  - [x] `argsort` (Quansight-Labs/uarray#155)
  - [x] `msort` (Quansight-Labs/uarray#155)
  - [x] `sort_complex` (Quansight-Labs/uarray#155)
  - [x] `partition` (Quansight-Labs/uarray#155)
  - [x] `argpartition` (Quansight-Labs/uarray#155)
- [x] [Searching](https://www.numpy.org/devdocs/reference/routines.sort.html#sorting)
  - [x] `argmax`
  - [x] `nanargmax` (#10)
  - [x] `argmin`
  - [x] `nanargmin` (#10)
  - [x] `argwhere` (#10)
  - [x] `nonzero` (#10)
  - [x] `flatnonzero` (#10)
  - [x] `where` (#10)
  - [x] `searchsorted` (#12)
  - [x] `extract` (#12)
- [x] [Counting](https://www.numpy.org/devdocs/reference/routines.sort.html#counting): `count_nonzero` (#16)

**Comment by hameerabbasi** [comment]
Searching and `pad` done!

**Comment by hameerabbasi** [comment]
Closed this since everything here is done.
